- become: yes
  hosts: all
  name: install_neovim

  tasks:
    - name: Install Dependencies 
      apt: name={{ item }} update_cache=no state=latest
      register: install_packages
      until: install_packages is not failed
      delay: 6
      retries: 100
      with_items:
        - gnupg2

    - name: Add Sury's APT repository (Ubuntu only?)
      apt_repository: repo=ppa:ondrej/php state=present update_cache=yes
  
    - name: Install Packages
      apt: name={{ item }} update_cache=no state=latest
      register: install_packages
      until: install_packages is not failed
      delay: 6
      retries: 100
      with_items:
        - php8.2
        - php8.2-apcu
        - php8.2-bcmath
        - php8.2-cli
        - php8.2-curl
        - php8.2-dev
        - php8.2-fpm
        - php8.2-gd
        - php8.2-gmp
        - php8.2-igbinary
        - php8.2-imap
        - php8.2-intl
        - php8.2-ldap
        - php8.2-mailparse
        - php8.2-mbstring
        - php8.2-memcached
        - php8.2-msgpack
        - php8.2-mysql
        - php8.2-opcache
        - php8.2-pcov
        - php8.2-rdkafka
        - php8.2-readline
        - php8.2-redis
        - php8.2-swoole
        - php8.2-sqlite3
        - php8.2-xml
        - php8.2-zip
      become: yes
