- become: yes
  hosts: all
  tasks:
    - name: Ensure group for user exists
      ansible.builtin.group:
        name: "{{ username }}"
        state: present
 
    - name: Create the user 
      user:
        name: "{{ username }}"
        shell: /bin/bash
        group: "{{ username }}"
        password: "{{ 'password' | password_hash('sha512') }}"

    - name: Ensure user is in the sudoers file
      lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        state: present
